---
- hosts: localhost
  become: true
  tasks:
    - name: Get Docker info
      community.docker.docker_info:
        docker_host: "tcp://host.docker.internal:2375"
      register: docker_info 
  
    - name: Pull the latest backend image
      community.docker.docker_image:
        name: "arturheath/pdbackend"
        tag: "latest"
        source: pull
        docker_host: "tcp://host.docker.internal:2375"
        tls: no

    - name: Ensure backend container is running
      docker_container:
        name: "pdbackend"
        image: "arturheath/pdbackend:latest"
        state: started
        restart_policy: always
        ports:
          - "8081:8081"

    - name: Pull the latest frontend image
      docker_image:
        name: "arturheath/pdfrontend"
        tag: "latest"
        source: pull

    - name: Ensure frontend container is running
      docker_container:
        name: "pdfrontend"
        image: "arturheath/pdfrontend:latest"
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
