version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres14
    environment:
      POSTGRES_DB: pdmovies
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/pgdata
    volumes:
      - postgres_data:/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
