INSERT INTO public.movies (id,"name","year",description,banner,category) VALUES
	 ('92553699-6397-4971-83b0-1d3f37fd62e5','Fight Club',1999,'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.','https://upload.wikimedia.org/wikipedia/pt/2/2b/FightClubPoster.jpg','DRAMA'),
	 ('02517b8e-22cb-4473-8e7a-a3e08d9f3081','The Shawshank Redemption',1994,'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.','https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg','DRAMA'),
	 ('c8b70202-706e-48b0-8a27-d65591b87caf','The Godfather',1972,'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.','https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg','DRAMA'),
	 ('8e8c4ccc-e085-4f58-bd26-5065222fe3d0','The Dark Knight',2008,'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.','https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg','ACTION'),
	 ('5996f009-f352-47df-b0f8-8cfcdaf45000','Schindler''s List',1993,'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.

','https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg','DRAMA'),
	 ('51d95a40-35d9-4d74-9ab2-92937f9396e3','The Godfather Part II',1974,'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.','https://upload.wikimedia.org/wikipedia/en/0/03/Godfather_part_ii.jpg','DRAMA'),
	 ('58cfc189-9bbf-4210-ae09-046858976916','The Lord of the Rings: The Return of the King',2003,'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.','https://upload.wikimedia.org/wikipedia/en/4/48/Lord_Rings_Return_King.jpg','FANTASY'),
	 ('64b915be-149b-45c2-8302-371224bac08e','Pulp Fiction',1994,'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.','https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg','DRAMA'),
	 ('b33ea623-0ff7-4e1c-9dc1-9bbe2e2b5a70','Forrest Gump',1994,'The history of the United States from the 1950s to the ''70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.','https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg','DRAMA'),
	 ('5e86dd23-ccdf-4cfe-a964-560dcf1cbafd','The Matrix',1999,'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.','https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg','ACTION');
